config/routes.rb
DailyDeals::Application.routes.draw do
  
  resources :writers

  resources :deals
  resources :comments
  resources :feeds
  resources :events do
    resources :registrations
  end
  
  resources :contacts 
  
  resources :magazines do
    member do
      post :copy
    end
  end
  
 get "mypages/darling"
 get "mypages/ding"
  
 match "feeds/recipes(.:format)"=>
 "feeds#recipes"
  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable , :polymorphic => true
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :recipes
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :selections
  has_many :products, :through => :selections
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :deal 
end

app/models/company.rb
class Company < ActiveRecord::Base
   has_many :addresses, :as => :addressable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :comments
end

app/models/dept.rb
class Dept < ActiveRecord::Base
    has_many :emps
end

app/models/emp.rb
class Emp < ActiveRecord::Base
  belongs_to :dept
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :registrations
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :studentus
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users , :through  => :memberships
  has_many :meetings
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  
  def to_s
    "#{Meeting.name}- #{pluralize(Meeting.count, 'meeting')} attending"
  end
end

app/models/people.rb
class People < ActiveRecord::Base
  has_many :addresses, :as => :addressable
end

app/models/person.rb
class Person < ActiveRecord::Base
  scope :teenagers, where("age<20 and age>12")
  scope :by_name , order(:name)
  scope :by_id 
  scope :name_starts_with, lambda { |query| where("name like  ?", "#{query}%" ) }  
end

app/models/product.rb
class Product < ActiveRecord::Base

  establish_connection :products
  
  validates :name , :apple=>true
end

app/models/reader.rb
class Reader < ActiveRecord::Base
     has_many :subscriptions
     has_many :magazines , :through => :subscriptions
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  belongs_to :author
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :cart
  
  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :meetings, :through => :groups
end

app/models/writer.rb
class Writer < ActiveRecord::Base
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  # GET /writers
  # GET /writers.json
  def index
    @writers = params[:admin] ? Writer.where(:admin=>true) : Writer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @writers }
      format.js
    end
  end

  # GET /writers/1
  # GET /writers/1.json
  def show
    @writer = Writer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @writer }
    end
  end

  # GET /writers/new
  # GET /writers/new.json
  def new
    @writer = Writer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @writer }
    end
  end

  # GET /writers/1/edit
  def edit
    @writer = Writer.find(params[:id])
  end

  # POST /writers
  # POST /writers.json
  def create
    @writer = Writer.new(params[:writer])

    respond_to do |format|
      if @writer.save
        format.html { redirect_to @writer, :notice => 'Writer was successfully created.' }
        format.json { render :json => @writer, :status => :created, :location => @writer }
      else
        format.html { render :action => "new" }
        format.json { render :json => @writer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /writers/1
  # PUT /writers/1.json
  def update
    @writer = Writer.find(params[:id])

    respond_to do |format|
      if @writer.update_attributes(params[:writer])
        format.html { redirect_to @writer, :notice => 'Writer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @writer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /writers/1
  # DELETE /writers/1.json
  def destroy
    @writer = Writer.find(params[:id])
    @writer.destroy

    respond_to do |format|
      format.html { redirect_to writers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@writer.errors.count, "error") %> prohibited this writer from being saved:</h2>

      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :admin %><br />
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/writers/_writer.erb
<li><%= link_to writer.name , writer %></li>

app/views/writers/edit.html.erb
<h1>Editing writer</h1>

<%= render 'form' %>

<%= link_to 'Show', @writer %> |
<%= link_to 'Back', writers_path %>

app/views/writers/index.html.erb
<h1>Listing writers</h1>

<table>
<%= link_to "Showing all (toggle)" , writers_path(:admin =>true) ,:remote=> true, :id=>'toggle'  %>	
<ul id='writer'>
	<%= render @writers%>	
</ul>

</table>
<br />

<%= link_to 'New Writer', new_writer_path %>

app/views/writers/index.js.erb
<% link_text = params[:admin] ? "Admins" : "all" %>

<% href = params[:admin] ? 
              writers_path : writers_path(:admin => true) %>

	
$("#toggle").html("Showing <%= link_text %> (toggle)");
$("#toggle").attr("href", "<%= href %>");
$("#writer").html('<%= escape_javascript(render @writers) %>');

app/views/writers/new.html.erb
<h1>New writer</h1>

<%= render 'form' %>

<%= link_to 'Back', writers_path %>

app/views/writers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @writer.name %>
</p>

<p>
  <b>Admin:</b>
  <%= @writer.admin %>
</p>


<%= link_to 'Edit', edit_writer_path(@writer) %> |
<%= link_to 'Back', writers_path %>