config/routes.rb
DailyDeals::Application.routes.draw do
  
  resources :writers

  resources :deals
  resources :comments
  resources :feeds
  resources :events do
    resources :registrations
  end
  
  resources :contacts 
  
  resources :magazines do
    member do
      post :copy
    end
  end
  
 get "mypages/darling"
 get "mypages/ding"
  
 match "feeds/recipes(.:format)"=>
 "feeds#recipes"
  

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable , :polymorphic => true
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :recipes
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :selections
  has_many :products, :through => :selections
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :deal 
end

app/models/company.rb
class Company < ActiveRecord::Base
   has_many :addresses, :as => :addressable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  has_many :comments
end

app/models/dept.rb
class Dept < ActiveRecord::Base
    has_many :emps
end

app/models/emp.rb
class Emp < ActiveRecord::Base
  belongs_to :dept
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :registrations
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :studentus
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users , :through  => :memberships
  has_many :meetings
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  include ActionView::Helpers::TextHelper
  
  def to_s
    "#{Meeting.name}- #{pluralize(Meeting.count, 'meeting')} attending"
  end
end

app/models/people.rb
class People < ActiveRecord::Base
  has_many :addresses, :as => :addressable
end

app/models/person.rb
class Person < ActiveRecord::Base
  scope :teenagers, where("age<20 and age>12")
  scope :by_name , order(:name)
  scope :by_id 
  scope :name_starts_with, lambda { |query| where("name like  ?", "#{query}%" ) }  
end

app/models/product.rb
class Product < ActiveRecord::Base

  establish_connection :products
  
  validates :name , :apple=>true
end

app/models/reader.rb
class Reader < ActiveRecord::Base
     has_many :subscriptions
     has_many :magazines , :through => :subscriptions
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ingredients
  belongs_to :author
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :cart
  
  has_many :memberships
  has_many :groups, :through => :memberships
  has_many :meetings, :through => :groups
end

app/models/writer.rb
class Writer < ActiveRecord::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
  	@deals = Deal.where("id>?" , 0)
  end
  
 def show
   @deals  = Deal.find_by_id( params[:id] )
 end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/index.html.erb
<h1>
	Nearby deals
</h1>

<% for deal in @deals %>
<ul>
	<li>
		<span>
		 <%= link_to  image_tag("http://a4.ak.lscdn.net/imgs/9fd65c2c-9924-4cc3-87a7-157fe7e636a0/85_q60_.jpg", :alt => "Deal" ,:size => "5*8") , deal_path(deal) , :id=>"deal_link"  %>
		</span>
		<h3>
			<%= link_to deal.name , deal_path(deal)%>
		</h3>	
		<p>
			<%=  link_to deals_size(deal.desc) , deal_path(deal) , :id => "deals_desc"%>
		</p>	
		<sup class="dollar_sign" id="sup_dollar">$</sup>
		<%= link_to deal.cost , deal_path(deal), :id => "cost_id" %>
		<%= button_to "view"   , deal_path(deal) ,:method => "get" ,:id => "button_view" %>
		<div id="deal" data-id="<%= deal.id   %>"/>
	
	</li>
	</p>		
</ul>  
<div id="comments">
	<%= render deal.comments %>
</div>
<% end %>

<script>	
$("#deal_link").hover(
  function () {
    	$("#deals_desc").hide();
		$("#button_view").hide();
		$("#cost_id").hide();
		$("#sup_dollar").hide();
  }
);

$(function(){
	setTimeout(updateComments,1000);
});

function updateComments(){
	var deal_id = $("#deal").attr("data-id");
    var after = $(".comment:last-child").attr("data-time");
	$.getScript("/comments.js?deal_id=" + deal_id +"&after=" + after)
	setTimeout(updateComments,1000);
}
</script>

app/views/deals/show.html.erb
<p>
  <b>Name:</b>
  <%= @deal.name %>
</p>